##################################################
#                                                #
# Part 2: k3s + 3 nginx                          #
#   - make destroy                               #
#   - make up                                    #
#                                                #
##################################################

## Config
SERVER_NODE_NAME = "tnardS"
SERVER_NODE_IP = "192.168.56.110"

MEM = "4096"
CPUS = "12" # (For 42 computers use only 1)

BOX = "bento/debian-12"
##

Vagrant.configure("2") do |config|
  config.vm.box = BOX 
	config.vm.box_check_update = false
  config.ssh.forward_agent = true
  
  # Creation of each VM
  
  config.vm.define SERVER_NODE_NAME do |server|
    server.vm.hostname = SERVER_NODE_NAME
    server.vm.network "private_network", ip: SERVER_NODE_IP
    server.vm.provider "virtualbox" do |vb|
      vb.memory = MEM
      vb.cpus = CPUS
    end

    server.vm.synced_folder ".", "/vagrant", type: "virtualbox" # Sync folder with host

    server.vbguest.auto_update = false

    server.vm.provision "shell", inline: <<-SHELL
      # Install K3s
      apt update -y && apt install curl -y
      
      export INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --tls-san #{SERVER_NODE_NAME} --advertise-address=#{SERVER_NODE_IP} --node-ip=#{SERVER_NODE_IP} --bind-address=#{SERVER_NODE_IP}"
      curl -sfL https://get.k3s.io | sh -
      
      # Alias kubectl
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc

      # Deploying 3 apps
      for i in 1 2 3
      do
        echo "Deploying of app $i in progress.." 
        /usr/local/bin/kubectl create configmap app$i.com --from-file /vagrant/confs/$i/index.html
        /usr/local/bin/kubectl apply -f /vagrant/confs/$i/deployment.yaml
        /usr/local/bin/kubectl apply -f /vagrant/confs/$i/service.yaml
        /usr/local/bin/kubectl apply -f /vagrant/confs/$i/ingress.yaml
      done
    SHELL
  end

end
