##################################################
#                                                #
# Part 1: Vagrant + K3s                          #
#   - make destroy                               #
#   - make up                                    #
#                                                #
##################################################

## Config
SERVER_NODE_NAME = "tnardS"
SERVER_NODE_IP = "192.168.56.110"

MEM = "2048"
CPUS = "4" # (For 42 computers use only 1)

BOX = "centos/8"
BOX_URL = "https://app.vagrantup.com/centos/boxes/8/versions/2011.0/providers/virtualbox.box"
##

## Remove firewall
$DISABLE_FIREWALL_SCRIPT = <<-SHELL
  sudo systemctl disable --now firewalld
SHELL
##

Vagrant.configure("2") do |config|
  config.vm.box = BOX
	config.vm.box_url = BOX_URL 
	config.vm.box_check_update = false
  config.ssh.forward_agent = true

	config.vm.provision "shell", inline: $DISABLE_FIREWALL_SCRIPT # Remove firewall

  config.vbguest.installer_hooks[:before_install] = [ # Fix for CentOS 8 (adding vault.centos.org to yum repos)
    'sudo sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*',
    'sudo sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*'
  ]

	config.vbguest.installer_options = { allow_kernel_upgrade: true }

  # Creation of each VM

  config.vm.define SERVER_NODE_NAME do |server|
    server.vm.hostname = SERVER_NODE_NAME
    server.vm.network "private_network", ip: SERVER_NODE_IP
    server.vm.provider "virtualbox" do |vb|
      vb.memory = MEM
      vb.cpus = CPUS
    end

    server.vm.synced_folder ".", "/vagrant", type: "virtualbox" # Sync folder with host

    server.vm.provision "shell", inline: <<-SHELL
      # Install K3s
      export INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --tls-san #{SERVER_NODE_NAME} --advertise-address=#{SERVER_NODE_IP} --node-ip=#{SERVER_NODE_IP} --bind-address=#{SERVER_NODE_IP}"
      curl -sfL https://get.k3s.io | sh -
      
      # Install net-tools (for ifconfig)
      sudo yum install net-tools -y
      
      # Alias kubectl
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc

      # Dump token to /vagrant/.token
      sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/.token

      # Deploying 3 apps
      for i in 1 2 3
      do
        echo "Deploying of app $i in progress.." 
        /usr/local/bin/kubectl create configmap app$i.com --from-file /vagrant/k3s/$i/index.html
        /usr/local/bin/kubectl apply -f /vagrant/k3s/$i/deployment.yaml
        /usr/local/bin/kubectl apply -f /vagrant/k3s/$i/service.yaml
        /usr/local/bin/kubectl apply -f /vagrant/k3s/$i/ingress.yaml
      done
    SHELL
  end

end
