SERVER_NODE_NAME = "tnardS"
SERVER_NODE_IP = "192.168.56.110"

WORKER_NODE_NAME = "tnardSW"
WORKER_NODE_IP = "192.168.56.111"

$DISABLE_FIREWALL_SCRIPT = <<-SHELL
  sudo systemctl disable --now firewalld
SHELL

MEM = "1024"
CPUS = "4"
BOX = "centos/8"
BOX_URL = "https://app.vagrantup.com/centos/boxes/8/versions/2011.0/providers/virtualbox.box"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
	config.vm.box_url = BOX_URL 
	config.vm.box_check_update = false
  config.ssh.forward_agent = true

	config.vm.provision "shell", inline: $DISABLE_FIREWALL_SCRIPT

  config.vbguest.installer_hooks[:before_install] = [
    'sudo sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*',
    'sudo sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*'
  ]

	config.vbguest.installer_options = { allow_kernel_upgrade: true }

  config.vm.define SERVER_NODE_NAME do |server|
    server.vm.hostname = SERVER_NODE_NAME
    server.vm.network "private_network", ip: SERVER_NODE_IP
    server.vm.provider "virtualbox" do |vb|
      vb.memory = MEM
      vb.cpus = CPUS
    end
    server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    server.vm.provision "shell", inline: <<-SHELL
      export INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --tls-san #{SERVER_NODE_NAME} --advertise-address=#{SERVER_NODE_IP} --node-ip=#{SERVER_NODE_IP} --bind-address=#{SERVER_NODE_IP}"
      echo $INSTALL_K3S_EXEC
      curl -sfL https://get.k3s.io | sh -
      sudo yum install net-tools -y
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc
      sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/token
    SHELL
  end

  config.vm.define WORKER_NODE_NAME do |serverworker|
    serverworker.vm.hostname = WORKER_NODE_NAME
    serverworker.vm.network "private_network", ip: WORKER_NODE_IP
    serverworker.vm.provider "virtualbox" do |vb|
      vb.memory = MEM
      vb.cpus = CPUS
    end
    serverworker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    serverworker.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/token
      export INSTALL_K3S_EXEC="agent --server https://#{SERVER_NODE_IP}:6443 --token-file /vagrant/token --node-ip=#{WORKER_NODE_IP}"
      curl -sfL https://get.k3s.io | sh -
      sudo yum install net-tools -y
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc
    SHELL

  end
end
