##################################################
#                                                #
# Part 1: Vagrant + K3s                          #
#   - make destroy                               #
#   - make up                                    #
#                                                #
##################################################

## Config
SERVER_NODE_NAME = "tnardS"
SERVER_NODE_IP = "192.168.56.110"

WORKER_NODE_NAME = "tnardSW"
WORKER_NODE_IP = "192.168.56.111"

MEM = "1024"
CPUS = "4" # (For 42 computers use only 1)

BOX = "debian/bookworm64"
##

Vagrant.configure("2") do |config|
  config.vm.box = BOX
	config.vm.box_check_update = false
  config.ssh.forward_agent = true

  # Creation of each VM

  config.vm.define SERVER_NODE_NAME do |server|
    server.vbguest.auto_update = false
    server.vm.hostname = SERVER_NODE_NAME
    server.vm.network "private_network", ip: SERVER_NODE_IP
    server.vm.provider "virtualbox" do |vb|
      vb.memory = MEM
      vb.cpus = CPUS
    end

    server.vm.synced_folder ".", "/vagrant", type: "virtualbox" # Sync folder with host

    server.vm.provision "shell", inline: <<-SHELL
      apt update -q && apt-get install -y inetutils-tools curl -q
      # Install K3s
      export INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --tls-san #{SERVER_NODE_NAME} --advertise-address=#{SERVER_NODE_IP} --node-ip=#{SERVER_NODE_IP} --bind-address=#{SERVER_NODE_IP}"
      echo test2
      curl -sfL https://get.k3s.io | sh -
      
      # Alias kubectl
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc

      # Dump token to /vagrant/.token
      sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/.token
      
      # Test to see if it fixes timeout issues
      systemctl restart k3s
    SHELL
  end

  config.vm.define WORKER_NODE_NAME do |serverworker|
    serverworker.vbguest.auto_update = false
    serverworker.vm.hostname = WORKER_NODE_NAME
    serverworker.vm.network "private_network", ip: WORKER_NODE_IP
    serverworker.vm.provider "virtualbox" do |vb|
      vb.memory = MEM
      vb.cpus = CPUS
    end
    
    serverworker.vm.synced_folder ".", "/vagrant", type: "virtualbox" # Sync folder with host

    serverworker.vm.provision "shell", inline: <<-SHELL
      apt update -q && apt-get install -y inetutils-tools curl -q
      # Install K3s
      export INSTALL_K3S_EXEC="agent --server https://#{SERVER_NODE_IP}:6443 --token-file /vagrant/.token --node-ip=#{WORKER_NODE_IP}"
      curl -sfL https://get.k3s.io | sh -

      # Alias kubectl
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc
    SHELL

  end
end
