##################################################
#                                                #
# Part 1: Vagrant + K3s                          #
#   - make destroy                               #
#   - make up                                    #
#                                                #
##################################################

## Config
SERVER_NODE_NAME = "tnardS"
SERVER_NODE_IP = "192.168.56.110"

WORKER_NODE_NAME = "tnardSW"
WORKER_NODE_IP = "192.168.56.111"

MEM = "2048"
CPUS = "4" # (For 42 computers use only 1)

BOX = "bento/debian-12"
##

Vagrant.configure("2") do |config|
  config.vm.box = BOX
	config.vm.box_check_update = false
  config.ssh.forward_agent = true

  # Creation of each VM

  config.vm.define SERVER_NODE_NAME do |server|
    server.vbguest.auto_update = false
    server.vm.hostname = SERVER_NODE_NAME
    server.vm.network "private_network", ip: SERVER_NODE_IP, bridge: "eth1"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = MEM
      vb.cpus = CPUS
      vb.name = SERVER_NODE_NAME
    end

    server.vm.synced_folder ".", "/vagrant", type: "virtualbox" # Sync folder with host

    server.vm.provision "shell", inline: <<-SHELL
      apt update -q && apt-get install -y inetutils-tools curl -q
      # Install K3s
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --node-external-ip=#{SERVER_NODE_IP}" sh -s -

      # Alias kubectl
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc

      # Dump token to /vagrant/.token
      sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/.token
    SHELL
  end

  config.vm.define WORKER_NODE_NAME do |serverworker|
    serverworker.vbguest.auto_update = false
    serverworker.vm.hostname = WORKER_NODE_NAME
    serverworker.vm.network "private_network", ip: WORKER_NODE_IP, bridge: "eth1"
    serverworker.vm.provider "virtualbox" do |vb|
      vb.memory = MEM
      vb.cpus = CPUS
    end
    
    serverworker.vm.synced_folder ".", "/vagrant", type: "virtualbox" # Sync folder with host

    serverworker.vm.provision "shell", inline: <<-SHELL
      apt update -q && apt-get install -y inetutils-tools curl -q
      # Install K3s
      curl -sfL https://get.k3s.io | K3S_URL=https://#{SERVER_NODE_IP}:6443 K3S_TOKEN=$(cat /vagrant/.token) sh -s -
      # Alias kubectl
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc
    SHELL

  end
end
