##################################################
#                                                #
# Part 3: K3d + Argo CD                          #
#   - make destroy                               #
#   - make up                                    #
#                                                #
##################################################

## Config
SERVER_NODE_NAME = "tnardS"
SERVER_NODE_IP = "192.168.56.110"

MEM = "2048"
CPUS = "4" # (For 42 computers use only 1)

BOX = "centos/8"
BOX_URL = "https://app.vagrantup.com/centos/boxes/8/versions/2011.0/providers/virtualbox.box"
##

## Remove firewall
$DISABLE_FIREWALL_SCRIPT = <<-SHELL
  sudo systemctl disable --now firewalld
SHELL
##

Vagrant.configure("2") do |config|
  config.vm.box = BOX
	config.vm.box_url = BOX_URL 
	config.vm.box_check_update = false
  config.ssh.forward_agent = true

	config.vm.provision "shell", inline: $DISABLE_FIREWALL_SCRIPT # Remove firewall

  config.vbguest.installer_hooks[:before_install] = [ # Fix for CentOS 8 (adding vault.centos.org to yum repos)
    'sudo sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*',
    'sudo sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*'
  ]

	config.vbguest.installer_options = { allow_kernel_upgrade: true }

  # Creation of each VM

  config.vm.define SERVER_NODE_NAME do |server|
    server.vm.hostname = SERVER_NODE_NAME
    server.vm.network "private_network", ip: SERVER_NODE_IP
    server.vm.provider "virtualbox" do |vb|
      vb.memory = MEM
      vb.cpus = CPUS
    end

    server.vm.synced_folder ".", "/vagrant", type: "virtualbox" # Sync folder with host

    server.vm.provision "shell", inline: <<-SHELL
      # Install docker
      curl -fsSL https://get.docker.com | sh -
      sudo usermod -aG docker $(whoami)
      sudo systemctl enable --now docker.service
      sudo systemctl enable --now containerd.service
      sudo systemctl start docker

      # Install K3d
      curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
      k3d cluster create dev-cluster --port 8080:80@loadbalancer --port 8888:8888@loadbalancer --port 8443:443@loadbalancer
      
      # Install kubectl
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
      echo "$(<kubectl.sha256) kubectl" | sha256sum --check
      # sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      chmod +x kubectl
      sudo mv ./kubectl /usr/local/bin

      # Install net-tools (for ifconfig)
      sudo yum install net-tools -y
      
      # Alias kubectl
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc
    SHELL
  end

end
